server:
  port: 8084

database:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  dbname: ${POSTGRES_DB}

monobank:
  token: ${MONOBANK_TOKEN}

logging:
  level: info